spring:
  application:
    name: common-service

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

  mail:
    host: smtp.gmail.com
    port: 587
    username: ngaysinh76@gmail.com
    password: kadp swbk hrmv dvzd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
