global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:9004"]

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:9002"]

  - job_name: "book-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["book-service:9001"]

  - job_name: "borrowing-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["borrowing-service:9003"]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:9005"]
